### ISSUE TITLE
error POST file to another URL 

### ISSUE THREAD

**Issue by ninepi09** [pqina/svelte-filepond#5] opened 2021-03-22 04:48 UTC
i use netlify as server, and want to upload the files to another URL with folder inside but 

i got this error in image : 

![svelte](https://user-images.githubusercontent.com/58588836/111941801-72f94180-8b04-11eb-88c1-f697dd26a53a.png)

what can i do to fix this ? thank you

**Comment by rikschennink** [comment] 2021-03-22 07:48
Hi, I don't know how file uploads work with Netlify, best to reach out to Netlify support about uploading formdata. As this is not a bug in FilePond I will close the issue.

**Closed as completed by rikschennink** 2021-03-22 07:48 UTC
